### ISSUE TITLE
Creare il modello per le carte di tutti giochi [UC01]

### ISSUE THREAD

**Issue by dstops** [alessioarcara/project_sweng#2]
_**Dod**_
- [x]  La pull request ha un titolo e descrizione adeguata
- [x]  La pull request è stata collegata con la issue del task
- [x]  I requisiti funzionali del task collegato sono soddisfatti
- [x]  Il codice si compila senza errori
- [x]  Gli Unit Tests sono stati scritti e passati 
- [x]  Gli Unit Tests esistenti sono stati passati
- [x]  La documentazione è stata aggiornata
- [x]  Il Code Review è stato fatto
- [x]  La pull request è stata accettata e fatto merge sul branch development.

 **Effort effettivo:** 
08/01: 30 m
09/01: 8 h

**Comment by alessioarcara** [comment]
Effort effettivo: 8 ore.
